shim:
  jquery:
    exports: '$'
    
modules:
  - name: 'Logger'
  - name: 'Utils'
    exclude: ['Logger']
  - name: 'CQ'
    exclude: ['Logger']
  - name: 'Backbone'
    exclude: ['Logger']
  - name: 'boot'
    exclude: ['main', 'Logger', 'Utils', 'CQ']
  - name: 'main'
    exclude: ['engine/engine', 'ui/ui', 'Logger', 'Utils', 'Backbone']
  - name: 'engine/engine'
    exclude: ['Logger', 'Utils', 'CQ']
  - name: 'ui/ui'
    exclude: ['Logger', 'Utils', 'Backbone', 'underscore']

paths:
  Logger: lib/console/console
  Utils: utils/utils
  CQ: lib/cq/cq
  underscore: lib/underscore/underscore
  Backbone: lib/backbone/backbone