optimize: 'uglify2'

shim:
  jquery:
    exports: '$'
  cq:
    exports: 'cq'
    
modules:
  - name: 'boot'

paths:
  logger: lib/console/console
  utils: utils/utils
  cq: lib/cq/canvasquery
  underscore: lib/underscore/underscore
  backbone: lib/backbone/backbone
  localstorage: lib/backbone/localstorage
  text: lib/text