shim:
  jquery:
    exports: '$'
    
modules:
  - name: 'utils'
  - name: 'cq'
  - name: 'backbone'
  - name: 'boot'
    exclude: ['main', 'utils', 'cq']
  - name: 'main'
    exclude: ['engine/engine', 'ui/ui', 'utils', 'backbone']
  - name: 'engine/engine'
    exclude: ['utils', 'cq']
  - name: 'ui/ui'
    exclude: ['engine/engine', 'utils', 'backbone', 'underscore']

paths:
  logger: lib/console/console
  utils: utils/utils
  cq: lib/cq/cq
  underscore: lib/underscore/underscore
  backbone: lib/backbone/backbone
  localstorage: lib/backbone/localstorage
  text: lib/text